# Generated by Django 5.0.1 on 2024-01-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_year_formed_band_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
    ]
