# Generated by Django 5.0.1 on 2024-01-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_year_formed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='year_formed',
        ),
    ]
