# Generated by Django 5.0.1 on 2024-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_band_year_formed'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLOT', 'Clothing'), ('POST', 'Posters'), ('MIS', 'Miscellaneous')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='band',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
