# Generated by Django 5.0.1 on 2024-01-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_band_description_band_sold_band_type_band_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('PO', 'Pop'), ('IP', 'Indie Pop'), ('CC', 'Contemporary Country'), ('AR', 'Alternative Rb')], default='', max_length=5),
        ),
    ]
