# Generated by Django 5.0.1 on 2024-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_band_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='biography',
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('PO', 'Pop'), ('IP', 'Indie Pop'), ('CC', 'Contemporary Country'), ('AR', 'Alternative Rb'), ('FP', 'Folk Pop')], default='', max_length=5),
        ),
    ]
