# Generated by Django 5.0.1 on 2024-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_band_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(null=True),
        ),
    ]
