# Generated by Django 5.0.1 on 2024-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_band_description_alter_band_official_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(default='', null=True),
        ),
    ]
