# Generated by Django 5.0.1 on 2024-01-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_singers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singers',
            name='band',
        ),
    ]
