# Generated by Django 5.0.1 on 2024-01-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_singers_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.singers'),
        ),
    ]
