# Generated by Django 5.0.1 on 2024-01-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_band_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='name',
        ),
    ]
