# Generated by Django 5.0.1 on 2024-01-22 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_remove_band_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='singers',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singers',
            name='description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='singers',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('PO', 'Pop'), ('IP', 'Indie Pop'), ('CC', 'Contemporary Country'), ('AR', 'Alternative Rb'), ('FP', 'Folk Pop')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='singers',
            name='official_homepage',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='singers',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
