# Generated by Django 5.0.1 on 2024-01-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_singers_active_singers_description_singers_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='active',
        ),
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.RemoveField(
            model_name='band',
            name='official_homepage',
        ),
    ]
