# Generated by Django 5.0.1 on 2024-01-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_band_active_remove_band_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
    ]
